[package]
name = "factr-provider-anthropic"
version = "0.1.0"
edition = "2024"

[dependencies]
factr-schema-dialect = { path = "../factr-schema-dialect" }
factr-logging = { path = "../factr-logging" }
factr-message-types = { path = "../factr-message-types" }
factr-provider-core = { path = "../factr-provider-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
